services:
  pandora-ui:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pandora-ui
    restart: unless-stopped
    ports:
      - "8093:80"
    environment:
      - VITE_API_URL=${VITE_API_URL:-https://pandora-dl.nscloud.my.id}
    mem_limit: 128m
    cpus: '0.5'
